[project]
name = "endoreg-db-api"
version = "0.1.0"
description = "EndoReg Db API Service"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "daphne>=4.1.2",
    "django>=5.1.3",
    "endoreg-db>=0.5.3",
    "psycopg==3.1.17", # Should be same version as version provided in devenv.nix
]

[tool.setuptools]
packages = ["endoreg_db_api"]